name: Deploy to EC2
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted  # Uses your EC2 runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install Nginx (if not present)
        run: |
          sudo yum install -y nginx || true
          sudo systemctl start nginx
      
      - name: Copy files to Nginx
        run: |
          sudo rm -rf /usr/share/nginx/html/*
          sudo cp -r . /usr/share/nginx/html/